# Generated by Django 4.0.1 on 2022-01-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
