# Generated by Django 4.0.1 on 2022-01-26 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_alter_category_options_alter_book_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'verbose_name': 'Checkout', 'verbose_name_plural': 'Checkout'},
        ),
    ]
