# Generated by Django 4.0.1 on 2022-02-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0010_alter_book_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutitem',
            name='due_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
