# Generated by Django 4.0.1 on 2022-02-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0011_checkoutitem_due_date_alter_book_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='checkoutitem',
            name='due_date',
            field=models.DateField(),
        ),
    ]
