# Generated by Django 4.0.1 on 2022-02-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0014_author_role_alter_book_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('image', models.CharField(max_length=500)),
                ('books', models.ManyToManyField(related_name='characters', to='library_app.Book')),
            ],
        ),
    ]
