# Generated by Django 4.0.1 on 2022-02-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0015_alter_book_description_alter_book_stock_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='checkoutitem',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
