# Generated by Django 4.0.1 on 2022-02-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0016_alter_book_stock_alter_checkoutitem_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='issueNumber',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='pageCount',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
