# Generated by Django 4.0.1 on 2022-02-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0017_book_issuenumber_book_pagecount_alter_book_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='issueNumber',
            new_name='issue_number',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='pageCount',
            new_name='page_count',
        ),
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
