# Generated by Django 4.0.1 on 2022-02-24 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0025_alter_book_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ('name',)},
        ),
    ]
